# Generated by Django 2.2.17 on 2020-11-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_scs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SFDF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jjh", models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="customtext",
            old_name="scs",
            new_name="schggjgjgkjhhjk",
        ),
    ]
