# Generated by Django 2.2.17 on 2020-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201111_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='QWE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjgjg', models.BigIntegerField()),
            ],
        ),
    ]
