# Generated by Django 2.2.17 on 2020-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_qwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='kjjkjjk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
